#spring:
#  application:
#    name: gao-nuoc-thien-an
#  profiles:
#    active: @spring.profiles.active@
#---
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/gaonuocthienan?createDatabaseIfNotExist=true
#    username: root
#    password: 12345678
#  jpa:
#    show-sql: false
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQLDialect
#  cache:
#    type: redis
#  data:
#    redis:
#      host: localhost
#      port: 6739
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: beetravel265@gmail.com
#    password: kdeeiymvieohkcyi
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#  main:
#    lazy-initialization: true
#  servlet:
#    multipart:
#      max-file-size: 40MB
#      max-request-size: 40MB
#  transaction:
#    default-timeout: 10
#    rollback-on-commit-failure: true
#  key:
#    param:
#      request: sndj3FSTW@*&%^%(*(@
#
#chat:
#  model: gpt-3.5-turbo-16k
#  api:
#    url: https://api.openai.com/v1/chat/completions
#    key: sdfhsfdj
#
#
## firebase
#bucketname:
#  firebase: gaonuocthienan-5b6c1.appspot.com
#URLupload:
#  firebase: https://firebasestorage.googleapis.com/v0/b/gaonuocthienan-5b6c1.appspot.com/o/%s?alt=media
#
#server:
#  servlet:
#    session:
#      cookie:
#        http-only: true
#      tracking-modes: cookie
#
#
#
#
